# Generated by Django 4.2 on 2023-11-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregister',
            name='jobtitle',
            field=models.CharField(max_length=50),
        ),
    ]
