# Generated by Django 4.2 on 2023-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_empregister_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregister',
            name='empoid',
            field=models.IntegerField(default=1),
        ),
    ]
