# Generated by Django 4.2 on 2023-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_empregister_empoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregister',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empregister',
            name='department',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empregister',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empregister',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empregister',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
